services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/youtube-search-api
        ports:
            - 8080:8000