services: 
    youtube-search-api:
        build: 
            context: .
            dockerfile: Dockerfile
        image: youtube-search-api
        command: 'php artisan serve --host=0.0.0.0'
        ports:
            - 8000:8000